# Generated by Django 5.0.2 on 2024-11-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_height_card_frame_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='agreement',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
