# Generated by Django 5.0.2 on 2024-11-07 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_users_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('Block', 'Block'), ('Friend', 'Friend'), ('FriendRequest', 'Friendrequest')], max_length=25)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('user_id_related', models.ForeignKey(db_column='user_id_related', on_delete=django.db.models.deletion.RESTRICT, related_name='user_id_related', to=settings.AUTH_USER_MODEL)),
                ('user_id_requester', models.ForeignKey(db_column='user_id_requester', on_delete=django.db.models.deletion.RESTRICT, related_name='user_id_requester', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_relationship',
            },
        ),
    ]
