# Generated by Django 5.0.2 on 2024-11-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usersrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersrelationship',
            name='relationship_type',
            field=models.CharField(choices=[('Block', 'Block'), ('Friend', 'Friend'), ('FriendRequest', 'Friendrequest'), ('Rejected', 'Rejected')], max_length=25),
        ),
    ]
