# Generated by Django 5.0.2 on 2024-11-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_usersrelationship_relationship_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='short_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='users',
            name='long_url',
        ),
    ]
