# Generated by Django 5.0.2 on 2024-11-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_short_url_users_url_remove_users_long_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersrelationship',
            name='activity_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
