# Generated by Django 5.0.2 on 2024-11-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_usersrelationship_activity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='long_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
